Develop
ofdun/bashnya_dz1 pull request #1
Opened 2023-10-31 19:54 UTC by ofdun

PR

2023-11-04 10:51 UTC, Yu-Leo requested changes
1. Подразумевается, что все программы в этом ДЗ пишутся не для последующего использования человеком, а для проверки автоматизированной тестирующей системой. Следствия из этого факта:
    - Не нужно выполнять проверки на корректность входных данных. Если в задании сказано, что вводится число, значит, после запуска программы будет введено число
    - Не нужно добавлять выводов с комметариями вида "Введите число" и т. д.
2. Когда поправишь все замечания, напиши, пожалуйста, в комментариях к PR слово "ИСПРАВЛЕНО", чтобы я видел, что можно ещё раз глянуть твоё решение.

2023-11-04 10:51 UTC, Yu-Leo commented on task-1/one.go
> +func calc_hypotenuse(a, b float64) float64 {
1. В Go переменные и функции принято именовать в `camelCase`. Глянь везде по коду
2. Можно использовать библиотечную ф-цию [Hypot](https://pkg.go.dev/math#Hypot)

2023-11-04 10:51 UTC, Yu-Leo commented on task-1/one.go
> +
Лишняя пустая строка

2023-11-04 10:51 UTC, Yu-Leo commented on task-1/one.go
> +	c := calc_hypotenuse(a, b)
Лишняя переменная, можно сразу выводить результат в `fmt.Println`

2023-11-04 10:51 UTC, Yu-Leo commented on task-2/two.go
> +	var a, b, c int16
Почему `int16`?

2023-11-04 10:51 UTC, Yu-Leo commented on task-2/two.go
> +
Лишняя пустая строка

2023-11-04 10:51 UTC, Yu-Leo commented on task-2/two.go
> +	return true
1. Можно убрать проверку на отрицательные числа (в задании сказано, что вводятся натуральные)
2. Можно убрать if-ы и оставить `return <выражение>`

2023-11-04 10:51 UTC, Yu-Leo commented on task-2/two.go
> +}
В конфе файлов принято оставлять пустую строку

2023-11-04 10:51 UTC, Yu-Leo commented on task-3/three.go
> +	fmt.Scan(&arr[0])
Хитро, но по заданию подразумевается, что необходимо считать массив в обычном порядке, сделать перестановку и затем вывести получившийся

2023-11-04 10:51 UTC, Yu-Leo commented on task-4/four.go
> +	fmt.Println("yes")
Судя по всему ты знаешь, что такое ф-ции и как их применять. В данном случае лучше создать ф-цию, которая проверяет, симметрична ли матрица, и возвращает bool значение. После чего, в зависимости от возвращаемого значения, выводить "yes" или "no"

2023-11-04 10:51 UTC, Yu-Leo commented on task-6/six.go
> +		if n > 0 {
Зачем эта проверка?

2023-11-04 10:51 UTC, Yu-Leo commented on task-6/six.go
> +				length += 1
Зачем этот счетчик? Ты можешь выводить длину `hashset`

2023-11-04 10:51 UTC, Yu-Leo commented on test.txt
> +test
Зачем этот файл?

2023-11-05 18:50 UTC, ofdun commented
ИСПРАВЛЕНО

2023-11-06 07:19 UTC, Yu-Leo commented
**Аппрув!** 🎆

2023-11-06 13:40 UTC, merged